#include "stdafx.h"
#include "control_robot.h"
#include "faza1.h"

//#include <math.h>

//#include "control_robotDoc.h"
//#include "control_robotView.h"
//#include "serialport.h"
//#include "serialport.cpp"



// faza1

faza1::faza1()
: m_motor(0)
{
}

faza1::~faza1()
{
}


// faza1 member functions

int faza1::back(int skuska, long double rambo)
{
	
	MessageBox(NULL,"fgfgf","fufu",MB_OK);
return 0;
}

void faza1::faza01(void)
{
/*
if(!(port.WriteByte(255))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
			            port.ClosePort();}
              else{
				if (!(port.WriteByte(1))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
                        port.ClosePort();}
              else{
				  if(!(port.WriteByte(CControl_robotView))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
			            port.ClosePort();}

/////////////////////////////////////Tretie servo
/////////////////////////////////////					
else{				
				if(!(port.WriteByte(255))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
			            port.ClosePort();}
              else{
				if (!(port.WriteByte(2))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
                        port.ClosePort();}
              else{
				if(!(port.WriteByte(CControl_robotView::m_servo2_vysledok))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
			            port.ClosePort();}

/////////////////////////////////////Stvrte servo
/////////////////////////////////////
else{
				if(!(port.WriteByte(255))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
			            port.ClosePort();}
              else{
				if (!(port.WriteByte(3))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
                        port.ClosePort();}
              else{
				if(!(port.WriteByte(CControl_robotView::m_servo3_vysledok))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
			            port.ClosePort();}
/////////////////////////////////////Piate servo
/////////////////////////////////////

else{
				if(!(port.WriteByte(255))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
			            port.ClosePort();}
              else{
				if (!(port.WriteByte(4))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
                        port.ClosePort();}
              else{
				if(!(port.WriteByte(CControl_robotView::m_servo4_vysledok))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
			            port.ClosePort();}
/////////////////////////////////////Sieste servo
/////////////////////////////////////
else{
				if(!(port.WriteByte(255))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
			            port.ClosePort();}
              else{
				if (!(port.WriteByte(5))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
                        port.ClosePort();}
              else{
				if(!(port.WriteByte(CControl_robotView::m_servo5_vysledok))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
			            port.ClosePort();}
/////////////////////////////////////Siedme servo
/////////////////////////////////////

else{
				if(!(port.WriteByte(255))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
			            port.ClosePort();}
              else{
				if (!(port.WriteByte(6))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
                        port.ClosePort();}
              else{
				if(!(port.WriteByte(CControl_robotView::m_servo6_vysledok))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
			            port.ClosePort();}
/////////////////////////////////////Osme servo
/////////////////////////////////////
else{
				if(!(port.WriteByte(255))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
			            port.ClosePort();}
              else{
				if (!(port.WriteByte(7))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
                        port.ClosePort();}
              else{
				if(!(port.WriteByte(CControl_robotView::m_servo7_vysledok))){
						MessageBox("Cannot Write to Port","Error",MB_OK+MB_ICONERROR);
			            port.ClosePort();}

        }	
		}
		}
			}	
		    }
		    }
        }	
		}
		}
			}	
		    }
		    }
			  }	
			  }
			  }
			    }
			    }
				} 
				  }
   				  }

*/
			      }
			      

