//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace orcs_mobile3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("orcs_mobile3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;SCRIPT LANGUAGE=&quot;JavaScript&quot;&gt;
        ///function Init() {
        ///    cvcs.RemoteHost = &quot;10.1.10.222&quot;
        ///    cvcs.RemoteWeb = 80
        ///    cvcs.RemotePort = 8481
        ///    cvcs.Timeout = 5
        ///    cvcs.AuthType = 1
        ///    cvcs.PreviewFrameRate = 1
        ///    cvcs.PreviewWidth = 400
        ///    cvcs.PreviewHeight = 300
        ///    cvcs.DeviceSerialNo = &quot;&quot;
        ///    window.setInterval(&quot;ShowFrameRate()&quot;, 1000)
        ///}
        ///
        ///function ShowFrameRate() {
        ///    if (0)
        ///    {
        ///       var fFrameRate = cvcs.FrameRate
        ///       window.status = &quot;Frame:&quot; + fFrameRate.toString() [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cam {
            get {
                return ResourceManager.GetString("cam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///
        ///&lt;body&gt;
        ///    
        ///&lt;b&gt;&lt;font size=&quot;7&quot;&gt;12
        ///      
        ///&lt;/font&gt;&lt;/b&gt;
        ///      
        ///&lt;/body&gt;
        ///&lt;/html&gt;
        ///.
        /// </summary>
        internal static string cam2 {
            get {
                return ResourceManager.GetString("cam2", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap letecka_2 {
            get {
                object obj = ResourceManager.GetObject("letecka_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mapa_areal_tuke {
            get {
                object obj = ResourceManager.GetObject("mapa_areal_tuke", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mapa_kosice {
            get {
                object obj = ResourceManager.GetObject("mapa_kosice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mapa_kosice_okolie {
            get {
                object obj = ResourceManager.GetObject("mapa_kosice_okolie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
