//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Robot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap _1gps3 {
            get {
                object obj = ResourceManager.GetObject("1gps3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap apply {
            get {
                object obj = ResourceManager.GetObject("apply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Battery {
            get {
                object obj = ResourceManager.GetObject("Battery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Battery2 {
            get {
                object obj = ResourceManager.GetObject("Battery2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Batterysmall {
            get {
                object obj = ResourceManager.GetObject("Batterysmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Batterysmall2 {
            get {
                object obj = ResourceManager.GetObject("Batterysmall2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;SCRIPT LANGUAGE=&quot;JavaScript&quot;&gt;
        ///function Init() {
        ///    cvcs.RemoteHost = &quot;10.1.10.222&quot;
        ///    cvcs.RemoteWeb = 80
        ///    cvcs.RemotePort = 8481
        ///    cvcs.Timeout = 5
        ///    cvcs.AuthType = 1
        ///    cvcs.PreviewFrameRate = 1
        ///    cvcs.PreviewWidth = 400
        ///    cvcs.PreviewHeight = 300
        ///    cvcs.DeviceSerialNo = &quot;&quot;
        ///    window.setInterval(&quot;ShowFrameRate()&quot;, 1000)
        ///}
        ///
        ///function ShowFrameRate() {
        ///    if (0)
        ///    {
        ///       var fFrameRate = cvcs.FrameRate
        ///       window.status = &quot;Frame:&quot; + fFrameRate.toString() [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cam {
            get {
                return ResourceManager.GetString("cam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;SCRIPT LANGUAGE=&quot;JavaScript&quot;&gt;
        ///function Init() {
        ///    cvcs.RemoteHost = &quot;10.1.10.222&quot;
        ///    cvcs.RemoteWeb = 80
        ///    cvcs.RemotePort = 8481
        ///    cvcs.Timeout = 5
        ///    cvcs.AuthType = 1
        ///    cvcs.PreviewFrameRate = 1
        ///    cvcs.PreviewWidth = 400
        ///    cvcs.PreviewHeight = 300
        ///    cvcs.DeviceSerialNo = &quot;&quot;
        ///    window.setInterval(&quot;ShowFrameRate()&quot;, 1000)
        ///}
        ///
        ///function ShowFrameRate() {
        ///    if (0)
        ///    {
        ///       var fFrameRate = cvcs.FrameRate
        ///       window.status = &quot;Frame:&quot; + fFrameRate.toString() [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cam2 {
            get {
                return ResourceManager.GetString("cam2", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap chip5 {
            get {
                object obj = ResourceManager.GetObject("chip5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap compass {
            get {
                object obj = ResourceManager.GetObject("compass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap compass1 {
            get {
                object obj = ResourceManager.GetObject("compass1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cpustat {
            get {
                object obj = ResourceManager.GetObject("cpustat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DossierFichier {
            get {
                object obj = ResourceManager.GetObject("DossierFichier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DossierFichier1 {
            get {
                object obj = ResourceManager.GetObject("DossierFichier1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap dowarrow1 {
            get {
                object obj = ResourceManager.GetObject("dowarrow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap downarrow2 {
            get {
                object obj = ResourceManager.GetObject("downarrow2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap energy {
            get {
                object obj = ResourceManager.GetObject("energy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap folder_slin_open {
            get {
                object obj = ResourceManager.GetObject("folder_slin_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap folder1 {
            get {
                object obj = ResourceManager.GetObject("folder1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap folder2 {
            get {
                object obj = ResourceManager.GetObject("folder2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Globe1 {
            get {
                object obj = ResourceManager.GetObject("Globe1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap GPS {
            get {
                object obj = ResourceManager.GetObject("GPS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap input_devices_settings {
            get {
                object obj = ResourceManager.GetObject("input_devices_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap kcmpci {
            get {
                object obj = ResourceManager.GetObject("kcmpci", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap leftarrow1 {
            get {
                object obj = ResourceManager.GetObject("leftarrow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap leftarrow2 {
            get {
                object obj = ResourceManager.GetObject("leftarrow2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap letecka_2 {
            get {
                object obj = ResourceManager.GetObject("letecka_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap linux {
            get {
                object obj = ResourceManager.GetObject("linux", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap linux2 {
            get {
                object obj = ResourceManager.GetObject("linux2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_Kaar {
            get {
                object obj = ResourceManager.GetObject("logo_Kaar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_sjf {
            get {
                object obj = ResourceManager.GetObject("logo_sjf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_TU {
            get {
                object obj = ResourceManager.GetObject("logo_TU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mapa_areal_tuke {
            get {
                object obj = ResourceManager.GetObject("mapa_areal_tuke", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mapa_kosice {
            get {
                object obj = ResourceManager.GetObject("mapa_kosice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mapa_kosice_okolie {
            get {
                object obj = ResourceManager.GetObject("mapa_kosice_okolie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mapa_kosice_okolie1 {
            get {
                object obj = ResourceManager.GetObject("mapa_kosice_okolie1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mapa_zlin {
            get {
                object obj = ResourceManager.GetObject("mapa_zlin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap math7 {
            get {
                object obj = ResourceManager.GetObject("math7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mic4 {
            get {
                object obj = ResourceManager.GetObject("mic4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap mw_joomla_logo {
            get {
                object obj = ResourceManager.GetObject("mw_joomla_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap OFF {
            get {
                object obj = ResourceManager.GetObject("OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ON {
            get {
                object obj = ResourceManager.GetObject("ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ON0 {
            get {
                object obj = ResourceManager.GetObject("ON0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ON2 {
            get {
                object obj = ResourceManager.GetObject("ON2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ON3 {
            get {
                object obj = ResourceManager.GetObject("ON3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ON4 {
            get {
                object obj = ResourceManager.GetObject("ON4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ON5 {
            get {
                object obj = ResourceManager.GetObject("ON5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ON9 {
            get {
                object obj = ResourceManager.GetObject("ON9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Openwrt_logo_small {
            get {
                object obj = ResourceManager.GetObject("Openwrt_logo_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap reload {
            get {
                object obj = ResourceManager.GetObject("reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap rightarrow1 {
            get {
                object obj = ResourceManager.GetObject("rightarrow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap rightarrow2 {
            get {
                object obj = ResourceManager.GetObject("rightarrow2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap robot_logo {
            get {
                object obj = ResourceManager.GetObject("robot_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap robot_logo1 {
            get {
                object obj = ResourceManager.GetObject("robot_logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap sebsoft_logo {
            get {
                object obj = ResourceManager.GetObject("sebsoft_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ServiceManager {
            get {
                object obj = ResourceManager.GetObject("ServiceManager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Services {
            get {
                object obj = ResourceManager.GetObject("Services", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap stop1 {
            get {
                object obj = ResourceManager.GetObject("stop1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string test3 {
            get {
                return ResourceManager.GetString("test3", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap tu3 {
            get {
                object obj = ResourceManager.GetObject("tu3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap tux {
            get {
                object obj = ResourceManager.GetObject("tux", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap uparrow1 {
            get {
                object obj = ResourceManager.GetObject("uparrow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap uparrow2 {
            get {
                object obj = ResourceManager.GetObject("uparrow2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap usb {
            get {
                object obj = ResourceManager.GetObject("usb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap webcam {
            get {
                object obj = ResourceManager.GetObject("webcam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap wifi2 {
            get {
                object obj = ResourceManager.GetObject("wifi2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap wifi2r {
            get {
                object obj = ResourceManager.GetObject("wifi2r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap wifi2y {
            get {
                object obj = ResourceManager.GetObject("wifi2y", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
